default_platform(:ios)

platform :ios do

  desc "Build iOS IPA"

  lane :build do

    sh("cd .. && flutter clean")
    sh("cd .. && flutter pub get")

    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store",
      clean: true,
      output_directory: "../build/ios/ipa",

      xcargs: "
        DEVELOPMENT_TEAM=59MQFXV295
        PRODUCT_BUNDLE_IDENTIFIER=com.rkandukuri.aijobsearch
        CODE_SIGN_STYLE=Automatic
      "
    )

  end

end