name: Flutter CI

on:
  push:
    branches:
      - main

jobs:

  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.0'
          channel: stable

      - name: Install Dependencies
        run: flutter pub get

      - name: Decode Apple Files
        env:
          IOS_KEY_BASE64: ${{ secrets.IOS_KEY_BASE64 }}
          IOS_CERT_BASE64: ${{ secrets.IOS_CERT_BASE64 }}
        run: |
          echo "$IOS_KEY_BASE64" | base64 --decode > ios.key
          echo "$IOS_CERT_BASE64" | base64 --decode > distribution.cer

      - name: Convert Certificate
        run: |
          openssl x509 -inform DER -in distribution.cer -out distribution.pem
          openssl pkcs12 -export \
            -out ios_certificate.p12 \
            -inkey ios.key \
            -in distribution.pem \
            -certpbe PBE-SHA1-3DES \
            -keypbe PBE-SHA1-3DES \
            -password pass:abc123

      - name: Decode Provisioning Profile
        env:
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/profile.mobileprovision

      - name: Setup Keychain
        env:
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          security create-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security import ios_certificate.p12 -k build.keychain -P "abc123" -A

      - name: Build Signed IPA
        run: flutter build ipa --release

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: build/ios/ipa/*.ipa